# Generated by Django 5.0.2 on 2024-03-03 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_alter_follower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
