# Generated by Django 5.0.2 on 2024-03-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_room_created_at_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='last_message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
