# Generated by Django 5.0.2 on 2024-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_room_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_room',
            name='last_message',
            field=models.TextField(default=None),
        ),
    ]
