# Generated by Django 5.0.2 on 2024-03-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_room_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
