# Generated by Django 5.0.2 on 2024-03-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat_room_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_room',
            name='last_message',
            field=models.TextField(default=''),
        ),
    ]
