# Generated by Django 5.0.2 on 2024-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='num_of_notification',
            field=models.IntegerField(default=0),
        ),
    ]
