# Generated by Django 5.0.2 on 2024-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_notification_num_of_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_notification',
            field=models.BooleanField(default=True),
        ),
    ]
