# Generated by Django 5.0.2 on 2024-03-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_notification_is_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='num_of_notification',
            new_name='num_of_notifications',
        ),
    ]
