# Generated by Django 5.0.2 on 2024-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_likes',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
