# Generated by Django 5.0.2 on 2024-03-02 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_post_likes_is_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Likes',
            new_name='Post_Like',
        ),
    ]
