# Generated by Django 5.0.2 on 2024-03-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_rename_post_likes_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_like',
            name='is_liked',
        ),
    ]
