# Generated by Django 5.0.2 on 2024-03-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
