# Generated by Django 5.0.2 on 2024-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_rename_post_id_post_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_like',
            old_name='post_id',
            new_name='post',
        ),
    ]
