# Generated by Django 5.0.2 on 2024-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_rename_post_id_post_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bio',
            field=models.TextField(),
        ),
    ]
