# Generated by Django 5.0.2 on 2024-02-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='file',
            field=models.FileField(upload_to='profiles'),
        ),
    ]
