# Generated by Django 5.0.2 on 2024-03-04 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_profilepic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilepic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
